### ISSUE TITLE
undefined constant IO::Timeout (Crystal version 0.34.0)

### ISSUE THREAD

**Issue by Tylerwbrown** [protoncr/tourmaline#14]
Looks like they changed the exception hierarchy in Crystal 0.34, so it made some breaking changes here, or at least in some of the dependencies (i.e halite/client.cr:160:17)

**Comment by Tylerwbrown** [comment]
Made a PR for a fix on the dependency, so I'm closing this issue since it's unrelated to this codebase.

For reference: https://github.com/icyleaf/halite/pull/83

**Comment by watzon** [comment]
Thanks!
