### ISSUE TITLE
Convenience class for paged messages using keyboards

### ISSUE THREAD

**Issue by watzon** [protoncr/tourmaline#22]
Had this idea earlier and figured it would be a good thing to get down here. The idea is to have a convenience class, maybe `PagedKeyboard` or something, which could be used to create a message with a keyboard featuring `<< Previous` and `Next >>` buttons (or something of the sort).

It is possible this could be a part of a larger convenience class for generating messages with keyboards that hold on to their own state.

**Comment by Poolitzer** [comment]
@watzon You know that this would mean it needs to have its own callback data and handler, which might conflict with the users one

**Comment by watzon** [comment]
Yeah I'd have to think about how best to implement it. For now it's just an idea, but I didn't want to forget.

**Comment by watzon** [comment]
Added this in e5b91c9. I'm pretty happy with how it turned out.
