### ISSUE TITLE
Error: undefined method 'persisted_users' for Tourmaline::NilPersistence (compile-time type is Tourmaline::Persistence+)

### ISSUE THREAD

**Issue by fenicks** [protoncr/tourmaline#24]
With the code below the `@persistence` instance is a _Tourmaline::JsonPersistence_: `#<Tourmaline::JsonPersistence:0x7f12bf279100 @filename="tourmaline_persistence.json", @persisted_users=`

I need to add `@persistence.as(Tourmaline::JsonPersistence)` to avoid the error: 

    Error: undefined method 'persisted_users' for Tourmaline::NilPersistence (compile-time type is Tourmaline::Persistence+)

```crystal
@[Command("seen")]
    def seen_command(client_, update)
      puts @persistence.inspect
      users = @persistence.as(Tourmaline::JsonPersistence).persisted_users.map(&.[1].username).join('\n')
      update.message.try &.reply(users)
    end
```

**Comment by watzon** [comment]
Thanks for this, I'll look into it

**Comment by watzon** [comment]
I'm starting to realize that the way I implemented Hash/Json persistence was not a great idea, at least not in trying to allow it to have methods different from the other persistence classes.

The easy, albeit messy, fix in this case is to use `.as` to make sure the compiler knows that `@persistence` is a `JsonPersistence` class. So the code should be:

```crystal
...
@persistence.as(JsonPersistence).persisted_users.map(&.[1].id).join('\n')
...
```

It's certainly not ideal, but Hash/Json persistence are the only ones that have those methods

**Comment by fenicks** [comment]
Ok, thanks.
