### ISSUE TITLE
Error: Proc(Log::Entry, IO, Nil) is not a module, it's a function

### ISSUE THREAD

**Issue by fenicks** [protoncr/tourmaline#29]
Got this error when trying to compile the new version

```
In lib/tourmaline/src/tourmaline/logger.cr:18:14

 18 | extend Log::Formatter
             ^-------------
Error: Proc(Log::Entry, IO, Nil) is not a module, it's a function
```

**Comment by watzon** [comment]
Are you using Crystal 0.35.0? Because in 0.34.0 `Log::Formatter` was a proc, but it's a module now.

**Comment by fenicks** [comment]
Effectively I'm using crystal 0.34.0.
I'll try with 0.35.0 but for now there are dependencies error in my project.

Thanks for the explanation.

**Comment by watzon** [comment]
@fenicks Yeah that should fix the issue
