### ISSUE TITLE
Update shards is not working with Crystal 0.35.0 or 0.35.1.

### ISSUE THREAD

**Issue by fenicks** [protoncr/tourmaline#30]
If you are experiencing `Unable to satisfy the following requirements` with crystal 0.35+, use crystal `shards update` command from version 0.34.0 and compile with crystal 0.35+ like : `/opt/crystal-0.35.1-1/bin/crystal build --no-debug --release -o bin/investbot src/main.cr`

![image](https://user-images.githubusercontent.com/336317/85254624-052ec500-b461-11ea-832e-711b5ccae583.png)

**Comment by watzon** [comment]
@fenicks I'll get it working today, thanks for all your bug reports!

**Comment by watzon** [comment]
Ok I got the `shard.yml` updated to say it supports 0.35.1 now. Also updated the `pool` dependency so it doesn't complain about a version mismatch between its `shard.yml` and its most recent release version.

If you run into this issue, delete your `shard.lock` and run `shards install` again. Everything should work.

**Comment by watzon** [comment]
I'm gonna go ahead and close this. Let me know if you're still having issues.
