### ISSUE TITLE
get_chat_member usage

### ISSUE THREAD

**Issue by Jacotsu** [protoncr/tourmaline#47]
Hi, i've just picked up crystal programming so this may be an incorrect usage, why do i have to manually bind the client in `get_chat_member`?
```
external_commenter = self.get_chat_member discussion_chat, sender
external_commenter.client = self
# Remove all permissions except message read/join
unless external_commenter.is_member
    external_commenter.restrict(false)
    msg.delete
end
```
The restrict method doesn't work unless i manually bind `external_commenter.client` with the client instance. Shouldn't `self.get_chat_member` automatically bind the client? Or maybe there is another way to change users permissions?

**Comment by watzon** [comment]
Probably a bug. I'll look into it, thanks :)

**Comment by watzon** [comment]
Apologies for taking so long on this, but the most recent release should fix this problem with `ChatMember` as well as every other model. Let me know if it's still an issue.
