### ISSUE TITLE
Mistake in `ChatMember` API docs

### ISSUE THREAD

**Issue by Jacotsu** [protoncr/tourmaline#50]
Some methods in the [ChatMember](https://tourmaline.dev/api_reference/Tourmaline/ChatMember/#Tourmaline::ChatMember#is_member) API doc are in the wrong category.
Methods such as:
- `is_member`
- `restrict`
- `status`
- `kick`
And others are not `USER API ONLY` and can be used by bots

**Comment by watzon** [comment]
Good catch
