### ISSUE TITLE
how to get username

### ISSUE THREAD

**Issue by NillyTheL0L** [protoncr/tourmaline#55]
hello im new on tourmaline and telegram how i got user username like:

Hello username! how are you?

note: im using this script
```sh
require "tourmaline"

class StudioBot < Tourmaline::Client
  @[Command("start")]
  def start_command(ctx)
    ctx.message.reply("Ola!, eu sou o studio bot mas pode me chamar de puppy, sou uma inteligencia artificial feita para te ajudar!, digite /ajuda para ver meus comandos e /catalogo para ver meus itens!")
  end

  @[Command("ajuda")]
    def ajuda_command(ctx)
    ctx.message.reply("Ola!, meus atuais comandos sao:
		/start - Mostra a mensagem do comeco
		/catalogo - Lhe da o nosso catalogo")
  end
end

bot = StudioBot.new(bot_token: "Secret Token LOL")
bot.poll
```
*Ignore what his says im brazilian*

**Comment by watzon** [comment]
`ctx.message.from` containst the `User` object, if it exists. So you'd need `ctx.message.from.try &.username` which is also a nilable object, so take care.

See: [Tourmaline::Handlers::CommandHandler::Context](https://tourmaline.dev/api_reference/Tourmaline/Handlers/CommandHandler/Context/#Tourmaline::Handlers::CommandHandler::Context#update)
